apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: tekton-kueue
    app.kubernetes.io/managed-by: kustomize
  name: webhook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webhook-role
subjects:
  - kind: ServiceAccount
    name: webhook
    namespace: system
