name: MultiKueue E2E Tests

on:
  pull_request:

env:
  KIND_EXPERIMENTAL_PROVIDER: podman
  IMG: konflux-ci.dev/tekton-kueue:${{ github.sha }}
  KUBECONFIG: /tmp/tekton-kueue/e2e/multikueue/multikueue.kubeconfig

jobs:
  test-e2e:
    name: Run MultiKueue E2E
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create MultiCluster Environment
        run: |
          hack/01-setup-multikueue.sh

      - name: Running MultiKueue e2e
        run: |
          go mod tidy
          go test ./test/e2e-multikueue/ -v -ginkgo.v
